debug: false

teleport:
  max-tries: 16
  # If player use /rtp command without given world
  # this world going to be used.
  default-world: world
  # If no safe random location is found after all attempts,
  # the player will be teleported to the configured fallback location.
  use-fallback-location: true
  cooldown-seconds: 30

  delay:
    enabled: true
    seconds: 5
    cancel-on-move: true
    notify:
      type: "actionbar" # message, title, actionbar, none
      message: "&eTeleporting in %s seconds..."
      subtitle: "&cDon't move" # If type is title
    sound:
      enabled: true
      name: "BLOCK_NOTE_BLOCK_PLING"
      pitch: 1.0
      volume: 1.0

  success:
    notify:
      type: "actionbar" # message, title, actionbar, none
      message: "&aYou have been teleported!"
      subtitle: "&eGood Luck!" # If type is title
    sound:
      enabled: true
      name: "BLOCK_NOTE_BLOCK_PLING"
      pitch: 1.0
      volume: 1.0
    particle: "CLOUD" # Leave "" if you want to disable the particles

worlds:
  world:
    radius: 1000
    min-y: 60
    max-y: 256
    # Teleport here if no safe random location could be found.
    fallback:
      x: 0.5
      y: 80.0
      z: 0.5
      yaw: 0.0
      pitch: 0.0

  world_nether:
    radius: 1000
    min-y: 30
    max-y: 120
    fallback:
      x: 100.5
      y: 64.0
      z: -100.5
      yaw: 180.0
      pitch: 0.0

version: '1'